### ISSUE TITLE
Networking issues

### ISSUE THREAD

**Issue by SneakyHub** [HirziDevs/PteroStats#13]
We have 2 nodes. 1 in canada 1 in germany. Our German node is using a tunnel from our France DDoS protected server using a local tunnel path to connect to the outside internet. Since this is the only route wings will operate on the bot isn't looking for it so it's giving a false positive saying it's offline.

Tunnel IP: 10.10.12.2
Public IP: 164.132.158.16

All traffic coming through 164.132.158.16 is communicating via 10.10.12.2 but for whatever reason the status bot isn't looking on 10.10.12.2 I can't find what it's looking for but I'm trying to fix it. thought I'd open an issue to make others aware of this issue.

**Comment by ShreshthTiwari** [comment]
The status bot uses the API of pterodactyl, if the api is not providing the api, the bot can't do anything.
Check if the api is working

**Comment by nickdevnl** [comment]
@SneakyHub still having issues or can this be closed?
