### ISSUE TITLE
how to setup pterostatus

### ISSUE THREAD

**Issue by aditya12311** [HirziDevs/PteroStats#15]

**Comment by tlkh40** [comment]
wrong place go to support server  ~~+ ratio + fell off~~

**Comment by acktarcodes** [comment]
Correct place

**Comment by ShreshthTiwari** [comment]
Discord server noob.
Come there and ask for help.

**Comment by ShreshthTiwari** [comment]
https://discord.gg/DAthQp7f

**Comment by acktarcodes** [comment]
or what... do something bout it

**Comment by ShreshthTiwari** [comment]
Or... Keep posting nobody will help you here.

**Comment by ShreshthTiwari** [comment]
Ok bye bye.
Discord server is made for a reason if you are soo dumb that you can't understand this.
We cannot help you.
This GitHub section clearly states ISSUES which means it is for ISSUES not for your dumb help in setting up the bot.

**Comment by HirziDevs** [comment]
indonesian hosting/store owner be like
