### ISSUE TITLE
Starting error 

### ISSUE THREAD

**Issue by Beastshubh** [HirziDevs/PteroStats#21]
![Screenshot_2022-11-11-21-29-25-48_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/117744152/201380591-608a7a17-085a-4100-b182-91e9062c0da1.jpg)
![Screenshot_2022-11-11-21-29-02-80_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/117744152/201380605-ebaf8d26-4c56-4f86-ab43-bb60085d1c16.jpg)

**Comment by OlekAleksander** [comment]
How did you fix this?

**Comment by Beastshubh** [comment]
> How did you fix this?

Idk

**Comment by HirziDevs** [comment]
Are you using the latest pterostats?, it's a problem with button components in discordjs 14 using `ButtonType.Link` instead of `LINK`
