### ISSUE TITLE
Issue with setting activity presence

### ISSUE THREAD

**Issue by Destarianon** [HirziDevs/PteroStats#23]
In the latest updates to discord.js activity presence has stopped working.
I believe it's an issue where v14 now requires the type field to be an integer to match the ActivityType enum.

A quick edit to the ready.js event to just manually set the type to 3 (watching) had the desired results.

**Comment by HirziDevs** [comment]
I forgot to change to ActivityType enum when updating to v14, it should be fixed now thanks.
