### ISSUE TITLE
Error when trying to start the bot

### ISSUE THREAD

**Issue by willypro7** [HirziDevs/PteroStats#24]
/PteroStats/node_modules/@discordjs/util/dist/index.js:34
  return () => defaultValue ??= cb();
                            ^^^

SyntaxError: Unexpected token '??='

**Comment by HirziDevs** [comment]
nodejs version?

**Comment by willypro7** [comment]
I have node 14, should I update to 16?

**Comment by HirziDevs** [comment]
> I have node 14, should I update to 16?

yes, discordjs v14 require nodejs 16
