### ISSUE TITLE
Getting problems at the refrest time

### ISSUE THREAD

**Issue by mariocr4ft** [HirziDevs/PteroStats#27]
The bot doesn't send nothing, and the console gives this error;
(node:25) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot execute action on a system message
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mariocr4ft** [comment]
@HirziDevs

**Comment by ShreshthTiwari** [comment]
@mariocr4ft the bot is trying to edit a system message make sure the channel has no other messages.
