### ISSUE TITLE
Invalid Form Body

### ISSUE THREAD

**Issue by Steephydra393** [HirziDevs/PteroStats#31]
Here is the [logs](https://pastebin.com/K9makE7f)
I've asked my host's support since PetroStats' Discord server is basicaly dead, they said the bot was broken.
I followed all the instructions the Github page supplied, your [website](https://pterostats.hirzidevs.xyz) is also broken.
I've tried to understand what the error is and its something about the Embed Form is invalid as the title says.

**Comment by ShreshthTiwari** [comment]
PteroStats is made for Pterodactyl panel not multicraft panel.
