### ISSUE TITLE
There is a bug where unknown numbers are displayed instead of ram and disk

### ISSUE THREAD

**Issue by PM-KIRILL** [HirziDevs/PteroStats#34]
There is a bug where unknown numbers are displayed instead of ram and disk
![IMG_20230731_040305](https://github.com/HirziDevs/PteroStats/assets/130344954/190298c3-6751-4b5c-87ad-72a37485bdaf)

**Comment by ShreshthTiwari** [comment]
Those are not unknown numbers that's how many resources you have allocated to those 2663 servers.
Pterostats does not calculate the system memory and disk usage it calculates how much is assigned to the server.
So yes literally why the hek have you made 2.6k server?

**Comment by PM-KIRILL** [comment]
Ok thanks for the help
