### ISSUE TITLE
After updating, get axios version error

### ISSUE THREAD

**Issue by wdhdev** [HirziDevs/PteroStats#36]
I have updated the bot using `git pull` and I am now receiving the following error:
```
Unsupported "axios" version!.
Please delete your "node_modules" and "package-lock.json".
And restart the bot.
Please make sure to check and remove "npm install" command from your startup params.
```

I have also tried deleting the entire bot, recloning the repository and I still get the same error.

**Comment by HirziDevs** [comment]
try manually install axios:

`npm install axios@1.6.3`

**Comment by wdhdev** [comment]
Yep, that worked! Thank you.
