### ISSUE TITLE
`ERROR` on node stats when no allocated memory/disk

### ISSUE THREAD

**Issue by wdhdev** [HirziDevs/PteroStats#37]
If you have not allocated any RAM or disk to a specific node (have all servers set to unlimited RAM/Disk on a node) it will show `ERROR` on node status.

![image](https://github.com/HirziDevs/PteroStats/assets/87287585/312a6ba3-22cb-45ed-9013-0756dee2f29c)

Node 1:
![image](https://github.com/HirziDevs/PteroStats/assets/87287585/6b4225df-672e-4ae8-ab30-70ef574c8d99)
Node 2:
![image](https://github.com/HirziDevs/PteroStats/assets/87287585/50d5856e-62fc-4f8e-ad9e-c9084df4ceb5)

**Comment by wdhdev** [comment]
@HirziDevs

**Comment by lezetho** [comment]
Can you enable debug mode and send the logs?

**Comment by lezetho** [comment]
Alright. No problem.
