### ISSUE TITLE
`feat`: combine setup.js and index.js into one file

### ISSUE THREAD

**Issue by lezetho** [HirziDevs/PteroStats#50]
It's really confusing having 2 files for setup, so what if we only had one? Basically if there isn't a file called .setup-complete in the directory then it'll run the setup script in the index.js file, and if there is a file called .setup-complete then it'll run the main file to start the bot. this'll stop confusion between the 2 files.

**Comment by lezetho** [comment]
i will make a development test soon.

**Comment by HirziDevs** [comment]
> i will make a development test soon.

Sorry I forgot to commit yesterday because I fell asleep, also thanks for the feedback!
