### ISSUE TITLE
PteroStats | Feather Applications integration 

### ISSUE THREAD

**Issue by RustinCassiem** [HirziDevs/PteroStats#7]
Hi 

I would like to know if there are future plans for developing integration for Microsoft Teams, Whatapp bot, email notification if when an application does go down

Thank you for an amazing application.

Kind Regards

**Comment by itsnotrin** [comment]
I'd be happy to make a PR for email notifications and look into Microsoft Teams if you're still interested? @RustinCassiem

**Comment by RustinCassiem** [comment]
sorry for a late reply, I'm very interested in seeing a PR on this

**Comment by ItzKazuki** [comment]
> Hi
> 
> I would like to know if there are future plans for developing integration for Microsoft Teams, Whatapp bot, email notification if when an application does go down
> 
> Thank you for an amazing application.
> 
> Kind Regards

you can use this https://hetrixtools.com/ if the node is down, it will send a notification to your email
