### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by kozamonq** [HirziDevs/PteroStats#8]
When I start the bot, I got this error :
`[PteroStats Debug] Error: Request failed with status code 403`
![unknown](https://user-images.githubusercontent.com/46488156/140074785-73b5ac49-ffed-4f39-ba4d-47d75d333422.png)

But I gave **Read** & **Write** permissions to the **Admin API**
Is it possible that this error occurs because the **panel** is not under **HTTPS**?
Or maybe because the **Panel URL** is an **IP** not a **domain** ?
Maybe **both** ?

**Comment by SteepoyTV** [comment]
same

**Comment by nickdevnl** [comment]
remake a admin api key

**Comment by HirziDevs** [comment]
Recreate admin apikey with all permission
